### PR TITLE
extend logging functionality

### PR DESCRIPTION
**Pull request by patrickkettner**
some extra features in logging I'd love to see added

### CODE REVIEW

**Comment by rubenv** [comment]
@patrickkettner could you recheck this PR and resolve the merge conflict?

**Comment by patrickkettner** [comment]
pushed the update, but github is having a service outage so it hasn't updated here. its [patrickkettner/grunt-git#cdf4eff](https://github.com/patrickkettner/grunt-git/commit/cdf4eff) for reference

**Comment by rubenv** [comment]
Merged, thanks!

**Comment by rubenv** [comment]
Released to NPM as `v1.0.3`.

**Comment by patrickkettner** [comment]
Thank you!

**Pull request merged**
