### PR TITLE
Make some default values case insensitive

### PR DESCRIPTION
**Pull request by speaktorob**

### CODE REVIEW

**Comment by rubenv** [comment]
How is uppercasing these values making it 'case insensitive'?

**Comment by speaktorob** [comment]
A fair question, but actually I got the description in the commit wrong. Git is case _sensitive_, so using 'head' by default would actually only work on case insensitive systems. I've corrected the commit message.

**Comment by rubenv** [comment]
Ah, that makes a lot of sense! Thanks for sending this in, will roll release!

**Comment by rubenv** [comment]
Released as `v1.0.4`.

**Pull request merged**
