### PR TITLE
Add 'force' and 'annotated' option to the gittag task

### PR DESCRIPTION
**Pull request by appconditioner**
Hi Ruben,

I added a force and an annotated option to the gittag task, since I needed this in our project. Maybe could be handy for others as well?

Best,
Rene

### CODE REVIEW

**Comment by rubenv** [comment]
@appconditioner Could you add a test as well?

**Comment by appconditioner** [comment]
Hi Ruben,

changed the position of the new options within command_tag.js and changed the 'force' option to be spawned as '--force' (just like in command_push.js). Also added three new tag command tests.

Best,
Rene

**Comment by appconditioner** [comment]
Hi Ruben,

also extended to README.md accordingly.

Rene

**Comment by rubenv** [comment]
Looking good! Merging & releasing!

**Comment by rubenv** [comment]
Released `v0.3.5`. Thanks a lot!

**Pull request merged**
